### ISSUE TITLE
建议 release build 中关闭混淆，便于其它开发者根据异常查找到源码

### ISSUE THREAD

**Issue by oasisfeng** [liangchenhe55/QQ-Notify-Evolution#15]
最近收到用户反馈此项目的 Nevolution 插件工作异常，但从 logcat 中只能的 crash stack 是有混淆的，难以对应到源码中，所以让我比较难分析是不是 Nevolution 升级引入的问题。

既然已经是开源项目，建议 release build 关闭混淆，只保留缩减（shrink）。理论上最终包大小为略微增加，但在应用市场普遍实现了 APK 增量下载的今天，这种影响对最终用户而言，已经比较小了。

**Comment by liangchenhe55** [comment]
好的 今晚我关了混淆重新编译一下发布。
顺便修几个遗留问题。
