### ISSUE TITLE
标题和内容拆分错误

### ISSUE THREAD

**Issue by Resurrection2981** [liangchenhe55/QQ-Notify-Evolution#2]
如图，不是在第一个冒号拆分的而是在最后一个冒号拆分标题和内容
![MVIMG_20191201_115837](https://user-images.githubusercontent.com/45873933/69909191-45c9e100-1432-11ea-8e74-7fb798bbc756.jpg)

**Comment by liangchenhe55** [comment]
感谢反馈。已确认是正则提取错误。
