### ISSUE TITLE
关联qq号正则问题

### ISSUE THREAD

**Issue by Resurrection2981** [liangchenhe55/QQ-Notify-Evolution#3]
乙给我发消息，没有读，切换到关联qq号，甲再给我发消息，QQ通知进化却显示的是乙的名字，甲的内容

**Comment by liangchenhe55** [comment]
感谢您的建议。 经网友提醒 在源项目没有放置开源协议的情况下默认不允许修改分发。因此现在将此仓库转为私有 并下架所有已发布的应用。在此对原作者致歉。

**Comment by liangchenhe55** [comment]
应该是已经修复了 [这里](https://github.com/liangchenhe55/QQ-Notify-Evolution/commit/1ec534e9ba9b6718d2d6e6e341963aff57d7f831)
